### ISSUE TITLE
iOS companion app for the leaderboard & motto list

### ISSUE THREAD

**Issue by kirknorthrop** [Lovely-Development-Team/MottoBotto#33]
We wanted an iOS app to display the results of the nominated mottos. How this would work is yet to be determined and very low priority.

**Comment by dwrss** [comment]
I mean...I'm onboard but what will it do?

**Comment by madi-vh** [comment]
I don't remember. But someone mentioned it.

**Comment by madi-vh** [comment]
See BappoAppo Repository.
